version: '3.8'
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
    driver: local